### ISSUE TITLE
Cannot install by GPM

### ISSUE THREAD

**Issue by diegomagikal** [clemdesign/grav-plugin-adsense#7]
Hi, 

It seems that installation by CLI is not working...

![image](https://user-images.githubusercontent.com/16082344/67170487-8ab91d00-f388-11e9-86c6-411fb0d8c804.png)

**Comment by clemdesign** [comment]
It seem that the rename operation is not yet taken into account: https://github.com/getgrav/grav/issues/2694
Please use manual installation for now.
