### ISSUE TITLE
Responsive width issue

### ISSUE THREAD

**Issue by estevez-dev** [clemdesign/grav-plugin-adsense#8]
Horizontal, vertical and square ads could be responsive, without strict size, but there is no way to set width: 100%, or unset it for ad container in plugin. That's why horizontal ad on desktop will not fit the screen on mobile and will be cropped.

**Comment by clemdesign** [comment]
Hi,

The plugin handle the sizes ads described in https://support.google.com/adsense/answer/185666?hl=en.
Responsive ads is not handled for now, except for InArticle ads.

**Comment by clemdesign** [comment]
Related to standard of sized ads, this request can't be implemented.

Define % in sized ads lead to breaks of ads.
