### ISSUE TITLE
This plugin does not work on Grav 1.7.XX

### ISSUE THREAD

**Issue by ganar** [clemdesign/grav-plugin-adsense#9]
The new Grav version breaks this plug-in and there is no way for me to understand what is wrong with the code.

Inserting the plugin on a template does not work: the css gets loaded, but that's about it. 

None of the code snippets in the docs produces the correct output on the page, must of them produce nothing. 

Sometimes setting the sandbox parameter  on the plugin will produce a broken image (it does not have an Address in the SRC of the img) but this works only once, and then disappears.

**Comment by clemdesign** [comment]
I use Grav 1.7.7 and I upgrade the test project to Grav v 1.7.12 (latest). The plugin works fine on both version, with my configuration of Grav project.

Check your JS integration, plugin configuration, system configuration...

**Comment by ganar** [comment]
We did.  We have two weeks trying.

We have a custom template built from scratch. The plugin is being executed but nothing comes out. The other stuff in the site is working with no issues. 

It fails when:

* Calling the plugin from content
* Calling the plugin form a partial in our template

We are going to test the setup with the default template, this is the last straw.

**Comment by jfboos007** [comment]
Hello Ganar,
did you find the way to make it work?

**Comment by clemdesign** [comment]
So, I have tested in 2 ways:
- by upgrading my test project to Grav 1.7.24 (lastest), no problem for me!
- by downloading new Grav project, deploy on local environment, install Quark theme and this plugin, then set-up the plugin: the plugin works fine! 

Note: You can use Page Ads and Auto Ads without modify your template, and this not need CSS. You shall modify your template only if you need to integrate Square Ad, Vertical Ad or Horizontal Ad.

I close this issue. If you are still facing to an operation issue, follow this:
- make sure you not have ad blocker enabled on your page.
- make sure you have wait 24-48H after create your ad in G Adsense.
- you are investigate on another plugins/themes which impact this plugin
